=== maxmouchet/vamk/XML/Assignment_2/airline.xsd
<?xml version="1.0"?>

<!-- journey.xsd -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"

  targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com"

  elementFormDefault="qualified">

  <xs:element name="airline">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="journeys">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="flight" maxOccurs="3">

                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="date" type="xs:date" />

                    <xs:element name="air_plane">

                      <!-- In the following we define valid values for element 
                        air_plane -->
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Airbus" />
                          <xs:enumeration value="Boeing" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>

                    <xs:element name="from" type="xs:string"
                      default="Vaasa" />
                    <xs:element name="to" type="xs:string" />
                    <xs:element name="duration" type="xs:integer"
                      fixed="18" />

                    <xs:element name="price" type="xs:decimal" />

                    <xs:element name="available_classes"
                      type="possible_classes" />

                  </xs:sequence>

                  <!--Here we define attribute id for element journey -->
                  <xs:attribute name="flight_number" type="xs:ID" />

                </xs:complexType>

              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="passengers">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="passenger" maxOccurs="5">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first_name" type="xs:string" />
                    <xs:element name="last_name" type="xs:string" />
                    <xs:element name="seat_position" type="possible_seat_position" />
                    <xs:element name="diet" type="possible_diet" />
                    <xs:element name="travelling_class"
                      type="possible_travelling_class" />
                  </xs:sequence>
                  <xs:attribute name="flight_number" type="xs:IDREF" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

  </xs:element>

  <xs:simpleType name="possible_seat_position">
    <xs:restriction base="xs:string">
      <xs:enumeration value="aisle" />
      <xs:enumeration value="window" />
      <xs:enumeration value="other" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="possible_diet">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vegetarian" />
      <xs:enumeration value="carnivore" />
      <xs:enumeration value="allergic" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="possible_travelling_class">
    <xs:restriction base="xs:string">
      <xs:enumeration value="first" />
      <xs:enumeration value="business" />
      <xs:enumeration value="touristic" />
    </xs:restriction>
  </xs:simpleType>


  <!-- In the following we define valid_classes data type -->
  <xs:simpleType name="possible_classes">

    <xs:restriction base="xs:integer">

      <xs:enumeration value="1" />

      <xs:enumeration value="2" />

      <xs:enumeration value="3" />

    </xs:restriction>

  </xs:simpleType>

</xs:schema>

=== maxmouchet/vamk/XML/Assignment_2/airline.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:airline xmlns:p="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com airline.xsd ">
  <p:journeys>
    <p:flight flight_number="idvalue0">
      <p:date>2001-01-01</p:date>
      <p:air_plane>Airbus</p:air_plane>
      <p:from>Vaasa</p:from>
      <p:to>Lyon</p:to>
      <p:duration>18</p:duration>
      <p:price>0.0</p:price>
      <p:available_classes>1</p:available_classes>
    </p:flight>
    <p:flight flight_number="idvalue1">
      <p:date>2001-01-01</p:date>
      <p:air_plane>Airbus</p:air_plane>
      <p:from>Vaasa</p:from>
      <p:to>Montreal</p:to>
      <p:duration>18</p:duration>
      <p:price>0.0</p:price>
      <p:available_classes>1</p:available_classes>
    </p:flight>
    <p:flight flight_number="idvalue2">
      <p:date>2001-01-01</p:date>
      <p:air_plane>Airbus</p:air_plane>
      <p:from>Vaasa</p:from>
      <p:to>Geneva</p:to>
      <p:duration>18</p:duration>
      <p:price>0.0</p:price>
      <p:available_classes>1</p:available_classes>
    </p:flight>
  </p:journeys>
  <p:passengers>
    <p:passenger flight_number="idvalue0">
      <p:first_name>Jean</p:first_name>
      <p:last_name>Dupont</p:last_name>
      <p:seat_position>aisle</p:seat_position>
      <p:diet>vegetarian</p:diet>
      <p:travelling_class>first</p:travelling_class>
    </p:passenger>
    <p:passenger flight_number="idvalue1">
      <p:first_name>Jeanne</p:first_name>
      <p:last_name>Duc</p:last_name>
      <p:seat_position>aisle</p:seat_position>
      <p:diet>vegetarian</p:diet>
      <p:travelling_class>first</p:travelling_class>
    </p:passenger>
    <p:passenger flight_number="idvalue2">
      <p:first_name>Marc</p:first_name>
      <p:last_name>Juan</p:last_name>
      <p:seat_position>aisle</p:seat_position>
      <p:diet>vegetarian</p:diet>
      <p:travelling_class>first</p:travelling_class>
    </p:passenger>
  </p:passengers>
</p:airline>
