=== maxmouchet/vamk/XML/Assignment_4/houses.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:element name="houses">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="house" maxOccurs="unbounded" type="houseType" />
			</xs:sequence>

		</xs:complexType>

	</xs:element>


	<!-- Here we define basicroomType for which we allow only four values: Bedroom, 
		Living room, Kitchen, Hall -->
	<xs:simpleType name="basicRoomType">

		<xs:restriction base="xs:string">

			<xs:enumeration value="Bedroom" />
			<xs:enumeration value="Living room" />
			<xs:enumeration value="Kitchen" />
			<xs:enumeration value="Hall" />
			<xs:enumeration value="Kid's Bedroom" />
			<xs:enumeration value="Office" />
		</xs:restriction>

	</xs:simpleType>

	<!-- Here we define complex roomType based on previously defined basicRoomType. -->
	<xs:complexType name="roomType">
		<xs:simpleContent>
			<xs:extension base="basicRoomType">
				<xs:attribute name="area" type="xs:float" use="required" />
				<xs:attribute name="unit" type="xs:string" use="optional" />
			</xs:extension>

		</xs:simpleContent>

	</xs:complexType>

	<xs:complexType name="addressType">

		<xs:sequence>

			<xs:element name="street" type="xs:string" />

			<xs:element name="postal_code" type="xs:integer" />

			<xs:element name="city" type="xs:string" />

			<xs:element name="country" type="xs:string" />

		</xs:sequence>

	</xs:complexType>

	<xs:simpleType name="saunaType">
		<xs:restriction base="xs:boolean" />
	</xs:simpleType>

	<xs:simpleType name="balconyType">
		<xs:restriction base="xs:boolean" />
	</xs:simpleType>

	<xs:complexType name="houseType">
		<xs:sequence>
			<xs:element name="address" type="addressType" />

			<xs:element name="room" type="roomType" minOccurs="2"
				maxOccurs="10" />

			<xs:element name="sauna" type="saunaType" minOccurs="0" />

			<xs:element name="balcony" type="balconyType" minOccurs="0" />
		</xs:sequence>

		<xs:attribute name="id" type="xs:ID" />
	</xs:complexType>

</xs:schema>

=== maxmouchet/vamk/XML/Assignment_4/houses.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<houses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

	xsi:noNamespaceSchemaLocation="houses.xsd">

	<house id="H1000">

		<address>

			<street>Sunny Street 8</street>

			<postal_code>65200</postal_code>

			<city>Vaasa</city>

			<country>Finland</country>

		</address>

		<room area="12.34" unit="square_meter">Kitchen</room>

		<room area="25.34">Bedroom</room>

		<sauna>true</sauna>

		<balcony>false</balcony>

	</house>

	<house id="H2000">

		<address>

			<street>Beach Street 6</street>

			<postal_code>65100</postal_code>

			<city>Stockholm</city>

			<country>Sweden</country>

		</address>

		<room area="16.00">Kitchen</room>

		<room area="30.40">Bedroom</room>

		<room area="15.30" unit="square_feet">Kid's Bedroom</room>

		<room area="45.80">Living room</room>

		<room area="65.20">Office</room>

	</house>

</houses>
