=== maxmouchet/vamk/XML/Assignment_3/company.dtd
<!ELEMENT company (employees, projects)>
<!ATTLIST company
	name CDATA #FIXED "Microsoft"
	phone CDATA #FIXED "0123456789"
	motto ENTITY #REQUIRED
>
<!ENTITY bwn "Be What's Next">

<!-- Main elements -->
<!ELEMENT employees (employee*)>
<!ELEMENT projects  (project*)>

<!-- Parameter entities -->
<!ENTITY % general_info "first_name, last_name">
<!ENTITY % date_format "format CDATA #FIXED 'yyyy-mm-dd'">
<!ENTITY % currency "currency CDATA #FIXED 'USD'">

<!-- Employee -->
<!ELEMENT employee (%general_info;, specialty, phone, salary)>
<!ATTLIST employee id ID #REQUIRED>

<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>

<!ELEMENT specialty (#PCDATA)>

<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone country_code CDATA #REQUIRED>

<!ELEMENT salary (#PCDATA)>
<!ATTLIST salary %currency;>

<!-- Project -->
<!ELEMENT project (name, manager, participants, starting_date, finishing_date, duration, budget)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT manager EMPTY>
<!ATTLIST manager id IDREF #REQUIRED>

<!ELEMENT participants (participant*)>

<!ELEMENT participant (hours)>
<!ATTLIST participant id IDREF #REQUIRED>
<!ELEMENT hours (#PCDATA)>

<!ELEMENT starting_date  (#PCDATA)>
<!ATTLIST starting_date %date_format;>
<!ELEMENT finishing_date (#PCDATA)>
<!ATTLIST finishing_date %date_format;>

<!ELEMENT duration (#PCDATA)>
<!ATTLIST duration unit CDATA #FIXED "hour">

<!ELEMENT budget   (#PCDATA)>
<!ATTLIST budget %currency;>

=== maxmouchet/vamk/XML/Assignment_3/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "company.dtd" >
<company motto="&bwn;" name="Microsoft" phone="0123456789">
  <employees>
    <employee id="1">
      <first_name>Jean</first_name>
      <last_name>Jacques</last_name>
      <specialty>Software Engineer</specialty>
      <phone country_code="33">664883710</phone>
      <salary currency="USD">15000</salary>
    </employee>
    <employee id="2">
      <first_name>Marie</first_name>
      <last_name>White</last_name>
      <specialty>Business Consultant</specialty>
      <phone country_code="358">864472275</phone>
      <salary currency="USD">20000</salary>
    </employee>
    <employee id="3">
      <first_name>Alex</first_name>
      <last_name>Should</last_name>
      <specialty>Project Management</specialty>
      <phone country_code="1">565772891</phone>
      <salary currency="USD">21000</salary>
    </employee>
  </employees>
  <projects>
    <project>
      <name>Windows 95</name>
      <manager id="3"/>
      <participants>
        <participant id="1">
          <hours>250</hours>
        </participant>
      </participants>
      <starting_date format="yyyy-mm-dd">1993-09-01</starting_date>
      <finishing_date format="yyyy-mm-dd">1995-12-24</finishing_date>
      <duration unit="hour">5000</duration>
      <budget currency="USD">1000000</budget>
    </project>
    <project>
      <name>Windows 3.11</name>
      <manager id="3"/>
      <participants>
        <participant id="1">
          <hours>350</hours>
        </participant>
        <participant id="2">
          <hours>150</hours>
        </participant>
      </participants>
      <starting_date format="yyyy-mm-dd">1990-07-01</starting_date>
      <finishing_date format="yyyy-mm-dd">1992-09-10</finishing_date>
      <duration unit="hour">3000</duration>
      <budget currency="USD">500000</budget>
    </project>
  </projects>
</company>
