=== maxmouchet/vamk/XML/Assignment_6/AssignVI-6.xsd
<?xml version="1.0"?>

<!-- AssignVI-6.xsd -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"

  targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com"

  elementFormDefault="qualified">

  <xs:element name="renting">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="movies">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="category" maxOccurs="3">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="movie" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="id" type="xs:ID" />
                          <xs:element name="name" type="xs:string" />
                          <xs:element name="director" type="xs:string"/>
                          <xs:element name="publication_year" type="xs:integer"/>
                          <xs:element name="duration" type="xs:integer"/>
                          <xs:element name="renting_price" type="xs:float"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" type="movie_category" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="customers">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="customer" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:ID" />
                    <xs:element name="first_name" type="xs:string" />
                    <xs:element name="last_name" type="xs:string" />
                    <xs:element name="rented_movies">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="rented_movie" maxOccurs="5">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:IDREF">
                                  <xs:attribute name="until" type="xs:date" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="rang" type="customer_rang" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
     </xs:complexType> 
  </xs:element>

  <xs:simpleType name="customer_rang">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ordinary" />
      <xs:enumeration value="privileged" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="movie_category">
    <xs:restriction base="xs:string">
      <xs:enumeration value="action" />
      <xs:enumeration value="drama" />
      <xs:enumeration value="horror" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== maxmouchet/vamk/XML/Assignment_6/AssignVI-6.xml
<?xml version="1.0"?>

<!-- AssignVI-6.xml -->
<renting xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com AssignVI-6.xsd">
  <movies>
    <category type="action">
      <movie>
        <id>m001</id>
        <name>Die Hard</name>
        <director>John McTiernan</director>
        <publication_year>1988</publication_year>
        <duration>125</duration>
        <renting_price>3.00</renting_price>
      </movie>
      <movie>
        <id>m002</id>
        <name>The Matrix</name>
        <director>The Wachowski Brothers</director>
        <publication_year>1999</publication_year>
        <duration>136</duration>
        <renting_price>3.50</renting_price>
      </movie>
    </category>
    <category type="drama">
      <movie>
        <id>m003</id>
        <name>The Godfather</name>
        <director>Francis Ford Coppola</director>
        <publication_year>1972</publication_year>
        <duration>175</duration>
        <renting_price>2.50</renting_price>
      </movie>
    </category>
    <category type="horror">
      <movie>
        <id>m004</id>
        <name>The Exorcist</name>
        <director>William Friedkin</director>
        <publication_year>1973</publication_year>
        <duration>122</duration>
        <renting_price>3.00</renting_price>
      </movie>
    </category>
  </movies>

  <customers>
    <customer rang="privileged">
      <id>c001</id>
      <first_name>John</first_name>
      <last_name>Doe</last_name>
      <rented_movies>
        <rented_movie until="2013-12-03">m004</rented_movie>
        <rented_movie until="2013-12-03">m001</rented_movie>
      </rented_movies>
    </customer>
    <customer rang="ordinary">
      <id>c002</id>
      <first_name>Jane</first_name>
      <last_name>Done</last_name>
      <rented_movies>
        <rented_movie until="2013-11-29">m002</rented_movie>
      </rented_movies>
    </customer>
  </customers>
</renting>
